language: java

cache:
  directories:
    - ~/.m2

addons:
  sonarcloud:
    organization: nortthon-github
    token:
      secure: "V/qw0ipRkv/itWjKW3Wn1JXfz8IbjKQxjcwup0jwj85vxmsT+cJrgt2GUv7LWpd1pORm6NtPMyPmoBuH1AUFu7Qe2U2VhClPW3ybkd00y6XA4eNx9Ogk2Pimlzr0OprB0BLYCotkDsr9zDdU10QqX0swjhli1L032WajtcLjJTA+xW2npi+2oBKJmf9jjSv4ZjsQsSJ4ifXqyE/EqK+rUrG5cFyWYU0e2QoOPlinUllwYMoxLNQOWT3Sg2Xq0/aTTIikdNUMccKs2tAo/vFygJ6tXFzjIl862wxigheSIwfJ8j7ckUQpcpY7tXm/D2JEhP6ziuY0VqoHQSr7ePjlDRJHuM9FLv4BVU8Fsof9s/g1pDzE4dn7GLognBm7AYiZY/W9Fyn0Yt6X1WI84hHeJs5je/pK2Yo6SETC6F6fqtGvT8MtuNeDnqkfaS4FXwvIgRL6/wwZvjDtkCUAIuCtWq8o5wfdB6ALIXblXlV4jk2Ye/4L3aKxvEWVchABNic4aSTHmkqBxqXVaAsSM4EbMxl6z6QECJbUltzE2Yp+qP1WoAARtu+rNj/Uu1xUq4DeqynFjAK63g/7OJomOXksOzTvwbYgz4tSYowHLZKSICLMCebLYLKozN2Pai++Par7VwEQbfzu8X6a9dsFOOeDU0VPFpn3VggpBocZ7Lf4QY0="

script:
  - "./mvnw verify sonar:sonar"

#after_success:
#  - ./mvnw clean test jacoco:report com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN
#  - ./mvnw clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
